### ISSUE TITLE
Download fails if the title includes a "#" symbol

### ISSUE THREAD

**Issue by fivestones** [johngully/overdrive-download#21]
Bug report: using the docker setup with docker-compose
if the title of the book includes a '#' symbol, the script cuts off the # and any words following, and then fails in with:
`Error: The title: "the book title upto the # symbol " could not be found. Please ensure you have borrowed the title and it is spelled correctly.`

**Comment by johngully** [comment]
@fivestones Do you have an example of a book with a `#` in the title.  It would be helpful to be able to test this scenario when implementing a fix.

**Comment by fivestones** [comment]
@johngully I sent you an email just now with the details of an example book.

**Comment by johngully** [comment]
Added support for special characters in book titles.  
@fivestones Feel free to pull the latest image from `DockerHub` and give it a try.

**Comment by fivestones** [comment]
Hi, @johngully, Thanks for this!
I pulled the latest image and it is still failing.
I get the following in the log after clicking download in the browser to download the book `Amazing Book (Amazing series #12`):

```
overdrivedownload-houston-server-1  | 2022-07-23T16:57:17.820972000Z > overdrivedownload@0.12.0 server
overdrivedownload-houston-server-1  | 2022-07-23T16:57:17.821265000Z > node web/server.mjs
overdrivedownload-houston-server-1  | 2022-07-23T16:57:19.680994000Z Overdrive Download server listening on port: 80
overdrivedownload-houston-server-1  | 2022-07-23T16:57:40.783645000Z / - url: "/"
overdrivedownload-houston-server-1  | 2022-07-23T16:57:40.794198000Z / - transferred "index.html"
overdrivedownload-houston-server-1  | 2022-07-23T16:59:56.750424000Z /download - url: "/download?title=Amazing%20Book%20(Amazing%20series%20"
overdrivedownload-houston-server-1  | 2022-07-23T17:00:21.810860000Z file:///usr/src/app/odm-download.mjs:231
overdrivedownload-houston-server-1  | 2022-07-23T17:00:21.811983000Z       throw new Error(`The title: "${title}" could not be found. Please ensure you have borrowed the title and it is spelled correctly.`)
overdrivedownload-houston-server-1  | 2022-07-23T17:00:21.812236000Z             ^
overdrivedownload-houston-server-1  | 2022-07-23T17:00:21.812557000Z Error: The title: "Amazing Book (Amazing series " could not be found. Please ensure you have borrowed the title and it is spelled correctly.
overdrivedownload-houston-server-1  | 2022-07-23T17:00:21.812711000Z     at OdmDownload._getTitle (file:///usr/src/app/odm-download.mjs:231:13)
overdrivedownload-houston-server-1  | 2022-07-23T17:00:21.812880000Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
overdrivedownload-houston-server-1  | 2022-07-23T17:00:21.813033000Z     at async OdmDownload._getDownloadForTitle (file:///usr/src/app/odm-download.mjs:193:26)
overdrivedownload-houston-server-1  | 2022-07-23T17:00:21.813213000Z     at async OdmDownload.download (file:///usr/src/app/odm-download.mjs:43:28)
overdrivedownload-houston-server-1  | 2022-07-23T17:00:21.813424000Z     at async OverdriveDownload.download (file:///usr/src/app/index.mjs:36:25)
overdrivedownload-houston-server-1  | 2022-07-23T17:00:21.813585000Z     at async file:///usr/src/app/web/server.mjs:53:18
overdrivedownload-houston-server-1  | 2022-07-23T17:00:21.813905000Z Node.js v17.9.1
overdrivedownload-houston-server-1 exited with code 1
```

I docker exec'd into the docker and did cat on the odm-download.mjs, to make sure it included your most recent changes. Around line 218 it has: 
```
let titleQuery = `h3[title]`
    if (title) {
      // Escape special characters in the book title. Added to address Issue #21 https://github.com/johngully/overdrive-download/issues/21
      const escapedTitle = title.replace(/[!"#$%&'()*+,.\/:;<=>?@[\\\]^`{|}~]/g, "\\$&");
      titleQuery = `h3[title="${escapedTitle}" i]`; // The "i" at the end of the selector makes the query case insensitive
    }
    logger.debug(`OdmDownload._getTitle - titleQuery: "${titleQuery}"`);
```
So I guess I have the new changes you made, but for some reason it's still not working for me.
Is there any other info I could give that would help fix this?

Thanks!

**Comment by johngully** [comment]
Looks like I had only corrected the download side of the problem.  The issue is related to the web page that displays the books that are on hold.

**Comment by johngully** [comment]
Added support for special characters in book titles **to the web interface**.
@fivestones Feel free to pull the latest image from DockerHub and give it another try.

**Comment by fivestones** [comment]
Ahhh, great, it's working like a charm now. Thanks again!
