### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by mts749** [johngully/overdrive-download#22]
I am having trouble installing odm, but I suspect the problem is elsewhere. I am posting here in case someone has seen something like this before and could provide assistance. Thanks in advance.

After successful installation:

```
->  npm install -g overdrivedownload

changed 205 packages, and audited 206 packages in 50s

41 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

```

I tried to run odm:

```
->  odm --help
node:fs:585
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open './utils/configurationInternal.schema.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at getJsonFromFile (file:///Users/mts/.node/lib/node_modules/overdrivedownload/utils/configuration.mjs:110:21)
    at getSchemas (file:///Users/mts/.node/lib/node_modules/overdrivedownload/utils/configuration.mjs:76:26)
    at new Configuration (file:///Users/mts/.node/lib/node_modules/overdrivedownload/utils/configuration.mjs:21:26)
    at file:///Users/mts/.node/lib/node_modules/overdrivedownload/cli.mjs:16:23
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './utils/configurationInternal.schema.json'
}

```

**Comment by johngully** [comment]
I was able to recreate the issue.  Seems like one of the files may not have made it into the the npm deployment.

👀 Looking into it.

**Comment by mts749** [comment]
Thanks!

**Comment by johngully** [comment]
`v13.1` Should resolve the issue with incorrect configuration schema paths when the CLI is installed globally.

@mts749 Please let me know if this corrects the issue for you.  Also be sure to run the `odm config` command to setup the CLI for your library
```bash
npm install -g overdrivedownload
odm config -l example-library-name -u example-username -p example-password -dl "./example/download/path"
odm "Title of book"
```

**Comment by mts749** [comment]
Yes, it is resolved. Many thanks.
